#!/bin/sh

#SBATCH --account=YourProject
#SBATCH --time=50:0:0
#SBATCH --mem-per-cpu=200M

source /cluster/bin/jobsetup

module purge   # clear any inherited modules
set -o errexit # exit on errors

arrayrun 1-200 workerscript
