#!/bin/bash

#SBATCH --account=YourProject
#SBATCH --time=1:0:0
#SBATCH --mem-per-cpu=2G

source /cluster/bin/jobsetup

module purge   # clear any inherited modules
set -o errexit # exit on errors

module load fsl/5.0.8

DATASET=dataset.$TASK_ID
OUTFILE=result.$TASK_ID

cp $DATASET $SCRATCH
cd $SCRATCH
chkfile $OUTFILE

YourProgram $DATASET > $OUTFILE
